; ================================
; PHP RUNNER - SANDBOX
; ================================

; Máximo de memoria que puede utilizar un script
memory_limit = 32M

; Tiempo máximo de ejecución
max_execution_time = 3

; Limitar el tamaño de datos recibidos
post_max_size = 32K

; Funciones que no queremos permitir

disable_functions = exec,shell_exec,system,passthru,popen